# name: Deploy Bot

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:

#     - name: executing remote ssh commands to deploy
#       uses: appleboy/ssh-action@v1.2.0
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USER }}
#         password: ${{ secrets.PASSWORD }}

#         script: |
#           cd chatbot/Chat-bot
#           git pull
#           export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
#           source venv/bin/activate
#           pip install -r requirements.txt
#           if [ -f /tmp/run.pid ]; then
#             kill $(cat /tmp/run.pid) || echo "No existing run.py process found."
#             rm /tmp/run.pid
#           fi
#           nohup python3.10 run.py > run.log 2>&1 &
#           echo $! > /tmp/run.pid




  
